version: '2'
services: 
    wordpress:
        image: wordpress:latest
        links:
         - db:mysql
        environment:
         - WORDPRESS_DB_PASSWORD=password
        volumes:
         - ./data/html:/var/www/html
    db:
        image: mariadb:latest
        environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=wordpress
        volumes:
         - ./data/database:/var/lib/mysql
         - ./data/src-database:/var/lib/mysql-src
        ports:
         - 3306:3306
    nginx: 
        image: nginx:latest
        links:
         - wordpress
        volumes:
          - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./data/html-static/localhost:/var/www/html/static
        ports:
          - 80:80
