name: WP-Staticfy
runtime: nodejs
description: A Pulumi program to deploy a static site
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-east-1
    static-website:targetDomain:
      description: The domain to serve the website at (e.g. www.example.com)
    static-website:pathToWebsiteContents:
      description: Relative path to the website's contents (e.g. the `./www` folder)
    static-website:certificateArn:
      description: (Optional) ACM certificate ARN for the target domain; must be in the us-east-1 region. If omitted, a certificate will be created.
    static-website:setupEmailForwarding: 
      description: (Optional) Setup email forwarding for the specified domain. If true then the following couple of fields need to be setup too
      default: false
    static-website:forwardTo:
      description: (Optional) Forward all email to this email
    static-website:forwardFromEmail:
      description: (Optional) Forward email from this email address. Must be part of the subdomain

